version: "3.3"
services:
  application:
    container_name: dashboard
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres-dashboard
    image: library/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped